name: Release

on:
  push:
    tags:
      - '*.*.*' # 1.2.3

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Create GitHub Release via gh
        shell: bash
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: gh release create "$TAG" --title "v$TAG" --generate-notes --fail-on-no-commits --draft

  docker:
    needs: [release]
    strategy:
      matrix:
        include:
          - tag: server-csharp
            dockerfile: csharp/src/InMemoryServer/Dockerfile
            context: ./csharp
          - tag: client-csharp
            dockerfile: csharp/src/CliClient/Dockerfile
            context: ./csharp
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: guitarrapc/actions/.github/actions/to-lower@main
        id: lower
        with:
          value: ${{ matrix.tag }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: |
            ${{ steps.lower.outputs.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest-${{ matrix.tag }}
            type=raw,value=${{ github.ref_name }}-${{ matrix.tag }}
            type=sha,enable=true,priority=100,suffix=-${{ matrix.tag }},format=short
      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.SYNCED_DOCKER_USER }}
          password: ${{ secrets.SYNCED_DOCKER_PASS }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Build and push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: "${{ matrix.dockerfile }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: "${{ matrix.context }}"
